name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        env:
          QODANA_TOKEN: ${{ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0IjoiM3lOS0UiLCJvcmdhbml6YXRpb24iOiIza1pPMCIsInRva2VuIjoiQURuYWoifQ.W5ZsLvlbQx_thirHkK0OYOawEYJXbTV-GrQhKL4NRiE }}